config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }
  # devise_for :users
  # scope "/admin" do
  #   resources :users
  # end
  class SubdomainConstraint
    def self.matches?(request)
      subdomains = %w{ www admin }
      request.subdomain.present? && !subdomains.include?(request.subdomain)
    end
  end
  # root to: 'home#index'
  root to: 'home#index'
  constraints SubdomainConstraint do
    resources :items do
      collection do
        get :search_items, :filter_items
      end
    end
    resources :orders do
      member do
        get :items, :complete
        put :order_dispatched
      end
      collection do
        get :search
      end
    end
    resources :order_items do
      collection do
        get :mark_complete
      end
      member do        
        put :change_quantity
      end

    end
    resources :calanders
  end
  resources :dashboards do
    collection do
      get :demo, format: :json
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/item.rb
class Item < ActiveRecord::Base
	validates :name, uniqueness: { case_sensitive: false }
	has_many :order_items
	has_many :orders, through: :order_items
	accepts_nested_attributes_for :order_items
	before_save :update_left, if: :quantity_changed?
	before_destroy :check_dependency
	self.per_page = 10	
	class << self
		def search_by(q)
			filter_items(q).map(&:view_format)
		end

		def filter_items(input)
			where("name ilike ?", "%#{input}%")
		end	
	end    

	def view_format
		{name: "#{name} (#{left})", id: id}
	end

	def update_left
		self.left = self.quantity
	end

	private
	def check_dependency
		orders = Order.where.not(status: ['Completed', 'In']).includes(:order_items).where("order_items.item_id" => 2)
		orders.any? ? self.errors[:base] << "Has dependency" : ''
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :authenticate_user!
	before_action :item, except: [:index, :create, :search_items]
	def index		
		@items = Item.paginate(page: params[:page] || 1, per_page: 10).order('updated_at DESC')
		if request.xhr?
			render json: {items: @items, next_page: @items.next_page, current_page: @items.current_page, previous_page: @items.previous_page}
		end
	end

	def search_items
		items = Item.search_by(params[:term])
		render json:  items
	end

	def filter_items
		items = Item.filter_items(params[:q]).paginate(:page => params[:page] || 1, :per_page => 10)
		render json: {items: items, next_page: items.next_page, current_page: items.current_page, previous_page: items.previous_page}
	end

	def new		
	end

	def edit
	end

	def create
		params[:item][:left] = params[:item][:quantity]
		@item = Item.new params[:item].permit!
		respond_to do |format|
			if @item.save			
				items = get_items
			    format.json { render json: {message: 'Product Added successfuly.', items: items, next_page: items.next_page, current_page: items.current_page, previous_page: items.previous_page} }
			else
				format.json { render json: {error: @item.errors.full_messages}, status: :unprocessable_entity}
			end
		end
	end

	def update
		respond_to do |format|
			if @item.update_attributes(params[:item].permit!)				
				items = get_items
				format.json { render json: {message: 'Product Updated successfuly.', items: items, next_page: items.next_page, current_page: items.current_page, previous_page: items.previous_page} }
			else		  
			  format.json { render json: {error: @item.errors.full_messages }	, status: :unprocessable_entity}
			end
		end
	end

	def destroy
		respond_to do |format|
			if @item.destroy
				items = get_items
				format.json { render json: {message: 'Product Deleted successfuly.', items: items, next_page: items.next_page, current_page: items.current_page, previous_page: items.previous_page} }
			else
				format.json { render json: {error: @item.errors.full_messages }	, status: :unprocessable_entity}
			end
		end
	end

	private
	def item
		@item ||= params[:id] ? Item.find(params[:id]) : Item.new 
	end

	def get_items
		Item.paginate(page: params[:page] || 1, per_page: 10).order('updated_at DESC')
	end

end

app/views/items/_form.html.erb
<div class="col-md-12 panel-default">
	<div class="panel panel-primary edit-list">
		<div class="panel-heading">Add/Edit Item</div>
		<div class="panel-body">
			<%= form_for @item, :html => {:class => "form-horizontal center"} do |f| %>
	  <div class="control-group">
		<div class="col-md-4">
		  <%= f.text_field :name, placeholder: "Name",class: "form-control" %>
	    </div>
	  </div>
	  <div class="control-group">		
		<div class="col-md-4">
		  <%= f.number_field :quantity, placeholder: "Quantity", class: "form-control" %>
	    </div>
	  </div>
	  <div class="form-group">
		<div class="col-md-4">
		  <%= f.number_field :charge, placeholder: "Charge/Day", class: "form-control" %>
	    </div>
	  </div>
	  <hr>
	  <div class="form-actions sv-btn">
	  	<a href="javascript:history.go(-1)">Cancel</a>
		<%= f.submit 'Save',class: "btn btn-default btn-primary"  %>
	  </div>
	<% end %>
		</div>
  </div>	
</div>

app/views/items/edit.html.erb
<%= render 'form' %>

app/views/items/index.html.erb
<%= react_component('Inventry', {items: @items, next_page: @items.next_page, current_page: @items.current_page, previous_page: @items.previous_page}) %>

app/views/items/index.html.old.erb
<div class="col-md-12">
  <h2>Items</h2>
 <button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">Add Item</button>
  <div class="panel panel-default">
    <div class="panel-body">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Quantity</th>
            <th>Left</th>
            <th>Charge (item/day)</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td><%= item.name %></td>
              <td><%= item.quantity %></td>
              <td><%= item.left %></td>
              <td><%= item.charge %></td>
              <td><%= link_to 'Edit', edit_item_path(item)  %> | <%= link_to 'Destroy', item_path(item),
            data: {:confirm => 'Are you sure?'}, :method => :delete %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>  
      <!-- Modal -->
      <div class="modal fade" id="myModal" tabIndex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="vertical-alignment-helper">
              <div class="modal-dialog vertical-align-center">
                  <div class="modal-content">
                      <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                          </button>
                           <h4 class="modal-title" id="myModalLabel">Modal title</h4>

                      </div>
                      <div class="modal-body">
                        <form action="/action_page.php">
                          <div class="form-group">
                            <label for="email">Email address:</label>
                            <input type="email" class="form-control" id="email">
                          </div>
                          <div class="form-group">
                            <label for="pwd">Password:</label>
                            <input type="password" class="form-control" id="pwd">
                          </div>
                          <div class="checkbox">
                            <label><input type="checkbox"> Remember me</label>
                          </div>
                          <button type="submit" class="btn btn-default">Submit</button>
                        </form>
                      </div>
                      <div class="modal-footer">
                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                          <button type="button" class="btn btn-primary">Save changes</button>
                      </div>
                  </div>
              </div>
          </div>
      </div>
</div>

app/views/items/new.html.erb
<!-- <div class="col-md-10 col-md-offset-1 panel-default">
	<div class="panel panel-primary">
		<div class="panel-heading">Simple Form: Inline Form</div>
		<div class="panel-body">
			<%= form_for @item, :html => {:class => "form-horizontal center"} do |f| %>
	  <div class="control-group">
		<div class="col-md-3">
		  <%= f.text_field :name,class: "form-control" %>
	    </div>
	  </div>
	  <div class="control-group">		
		<div class="col-md-3">
		  <%= f.number_field :quantity,class: "form-control" %>
	    </div>
	  </div>
	  <div class="form-group">
		<div class="col-md-3">
		  <%= f.number_field :charge,class: "form-control" %>
	    </div>
	  </div>
	  <div class="form-actions">
		<%= f.submit 'Save',class: "btn btn-default btn-primary"  %>
	  </div>
	<% end %>
		</div>
  </div>	
</div> -->
<%= render 'form' %>