config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }
  # devise_for :users
  # scope "/admin" do
  #   resources :users
  # end
  class SubdomainConstraint
    def self.matches?(request)
      subdomains = %w{ www admin }
      request.subdomain.present? && !subdomains.include?(request.subdomain)
    end
  end
  # root to: 'home#index'
  root to: 'home#index'
  constraints SubdomainConstraint do
    resources :items do
      collection do
        get :search_items, :filter_items
      end
    end
    resources :orders do
      member do
        get :items, :complete
        put :order_dispatched
      end
      collection do
        get :search
      end
    end
    resources :order_items do
      collection do
        get :mark_complete
      end
      member do        
        put :change_quantity
      end

    end
    resources :calanders
  end
  resources :dashboards do
    collection do
      get :demo, format: :json
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/helpers/layout_helper.rb
module LayoutHelper
  def flash_messages(opts={})
    @layout_flash = opts.fetch(:layout_flash) { true }

    capture do
      flash.each do |name, msg|
        concat content_tag(:div, msg, id: "flash_#{name}")
      end
    end
  end

  def show_layout_flash?
    @layout_flash.nil? ? true : @layout_flash
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>T&C</title>
	  <%= stylesheet_link_tag    'application', media: 'all' %>
	  <%= javascript_include_tag 'application' %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<div class="top-header">
			<header class="container">
			  <nav class="navbar navbar-default">
			    <div class="navbar-header">
			      <%= link_to 'T&C', root_path, class: 'navbar-brand' %>
			    </div>
			    <% if user_signed_in? %>
			      <div class="pull-right right-buttons">

			      	<ul class="lst-item">
			      		   <li><a href="/items"><i aria-hidden="true" class="fa fa-plus-circle"></i> <span>Inventory</span><a/></li>

			      		   <li><a href="/items/new"><i aria-hidden="true" class="fa fa-plus-circle"></i> <span>Add Item</span></a></li>
			      		   <li><a href="/orders"><i aria-hidden="true" class="fa fa-plus-circle"></i> <span>Orders</span><a/></li>
			      		   <li><a href="/orders/new"><i aria-hidden="true" class="fa fa-plus-circle"></i> <span>New Order</span></a></li>
			      	</ul>

			        <%= link_to 'Sign out', destroy_user_session_path, method: 'delete', class: 'btn btn-default navbar-btn logout' %>
			      </div>
			    <% elsif admin_signed_in? %>
			      <div class="pull-right right-buttons">

			      	<ul class="lst-item">
			      		   <li><a href="/dashboards"><i aria-hidden="true" class="fa fa-plus-circle"></i> <span>Accounts</span></a></li>
			      		   <li><a href="/users/sign_up"><i aria-hidden="true" class="fa fa-plus-circle"></i> <span>New Account</span><a/></li>
			      	</ul>

			        <%= link_to 'Sign out', destroy_user_session_path, method: 'delete', class: 'btn btn-default navbar-btn logout' %>
			      </div>    		      
			    <% end %>
			  </nav>
			</header>
		</div>
		<div class="container">
		  <%= flash_messages if show_layout_flash? %>
		  <div class="row">
		    <%= yield %>
		  </div>
		</div>
	  <!-- <p class="notice"><% notice %></p>
	  <p class="alert"><% alert %></p> -->      
		<div class="footer">
		  <p>Footer</p>
		</div>
  </body>
</html>

</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>T&C</title>
	  <%= stylesheet_link_tag    'application', media: 'all' %>
	  <%= javascript_include_tag 'application' %>
	  <%= csrf_meta_tags %>
	</head>
	<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60">
		<nav class="navbar navbar-default navbar-fixed-top">
		  <div class="container">
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>                        
		      </button>
		      <a class="navbar-brand" href="#myPage">T&C</a>
		    </div>
		    <div class="collapse navbar-collapse" id="myNavbar">
		      <ul class="nav navbar-nav navbar-right">
		        <li><a href="#about">ABOUT</a></li>
		        <li><a href="#services">WHY T&C</a></li>
		        <li><a href="#testimonial">TESTIMONIAL</a></li>
		        <li><a href="#pricing">PRICING</a></li>
		        <li><a href="#contact">CONTACT</a></li>
		      </ul>
		    </div>
		  </div>
		</nav>		
		<div id="about" class="container-fluid bg-grey">
		  <div class="row">
		    <div class="col-sm-8">		      
		      <p>T&C is for managing and helping your tant and catering buisness. T&C will manage your inventory and order.</p>
		      <br><button class="btn btn-default btn-lg">Get in Touch</button>
		    </div>
		    <div class="col-sm-4">
		      <span class="glyphicon glyphicon-signal logo"></span>
		    </div>
		  </div>
		</div>

		<!-- Container (Services Section) -->
		<div id="services" class="container-fluid text-center">
		  <h2>WHY USE T&C</h2>
		  <h4>What we offer</h4>
		  <br>
		  <div class="row slideanim">
		    <div class="col-sm-4">
		      <span class="glyphicon glyphicon-off logo-small"></span>
		      <h4>Easy to use</h4>
		      <p>Lorem ipsum dolor sit amet..</p>
		    </div>
		    <div class="col-sm-4">
		      <span class="glyphicon glyphicon-heart logo-small"></span>
		      <h4>No need to check availablity for item</h4>
		      <p>Lorem ipsum dolor sit amet..</p>
		    </div>
		    <div class="col-sm-4">
		      <span class="glyphicon glyphicon-lock logo-small"></span>
		      <h4>Pay per use</h4>
		      <p>Lorem ipsum dolor sit amet..</p>
		    </div>
		  </div>
		  <br><br>
		  <div class="row slideanim">
		    <div class="col-sm-4">
		      <span class="glyphicon glyphicon-leaf logo-small"></span>
		      <h4>Low cost</h4>
		      <p>Lorem ipsum dolor sit amet..</p>
		    </div>
		    <div class="col-sm-4">
		      <span class="glyphicon glyphicon-certificate logo-small"></span>
		      <h4>24/7 Support</h4>
		      <p>Lorem ipsum dolor sit amet..</p>
		    </div>
		    <div class="col-sm-4">
		      <span class="glyphicon glyphicon-wrench logo-small"></span>
		      <h4 style="color:#303030;">Trusted by manay Clients</h4>
		      <p>Lorem ipsum dolor sit amet..</p>
		    </div>
		  </div>
		</div>

		<!-- Container (Portfolio Section) -->
		<div id="testimonial" class="container-fluid text-center bg-grey">
		  <h2>What our customers say</h2>
		  <div id="myCarousel" class="carousel slide text-center" data-ride="carousel">
		    <!-- Indicators -->
		    <ol class="carousel-indicators">
		      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
		      <li data-target="#myCarousel" data-slide-to="1"></li>
		      <li data-target="#myCarousel" data-slide-to="2"></li>
		    </ol>

		    <!-- Wrapper for slides -->
		    <div class="carousel-inner" role="listbox">
		      <div class="item active">
		        <h4>"This company is the best. I am so happy with the result!"<br><span>Michael Roe, Vice President, Comment Box</span></h4>
		        <!-- <img src="../assets/img.jpg"> -->
		      </div>
		      <div class="item">
		        <h4>"One word... WOW!!"<br><span>John Doe, Salesman, Rep Inc</span></h4>
		        <!-- <img src="../assets/img1.jpg"> -->
		      </div>
		      <div class="item">
		        <h4>"Could I... BE any more happy with this company?"<br><span>Chandler Bing, Actor, FriendsAlot</span></h4>
		      </div>
		    </div>

		    <!-- Left and right controls -->
		    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
		      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
		      <span class="sr-only">Previous</span>
		    </a>
		    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
		      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
		      <span class="sr-only">Next</span>
		    </a>
		  </div>
		</div>

		<!-- Container (Pricing Section) -->
		<div id="pricing" class="container-fluid">
		  <div class="text-center">
		    <h2>Pricing</h2>
		    <h4>Choose a payment plan that works for you</h4>
		  </div>
		  <div class="row slideanim">
		    <div class="col-sm-4 col-xs-12">
		      <div class="panel panel-default text-center">
		        <div class="panel-heading">
		          <h1>Basic</h1>
		        </div>
		        <div class="panel-body">
		          <p><strong>20</strong> Lorem</p>
		          <p><strong>15</strong> Ipsum</p>
		          <p><strong>5</strong> Dolor</p>
		          <p><strong>2</strong> Sit</p>
		          <p><strong>Endless</strong> Amet</p>
		        </div>
		        <div class="panel-footer">
		          <h3>$19</h3>
		          <h4>per month</h4>
		          <button class="btn btn-lg btn-outline-info">Sign Up</button>
		        </div>
		      </div>      
		    </div>     
		    <div class="col-sm-4 col-xs-12">
		      <div class="panel panel-default text-center">
		        <div class="panel-heading">
		          <h1>Pro</h1>
		        </div>
		        <div class="panel-body">
		          <p><strong>50</strong> Lorem</p>
		          <p><strong>25</strong> Ipsum</p>
		          <p><strong>10</strong> Dolor</p>
		          <p><strong>5</strong> Sit</p>
		          <p><strong>Endless</strong> Amet</p>
		        </div>
		        <div class="panel-footer">
		          <h3>$29</h3>
		          <h4>per month</h4>
		          <button class="btn btn-lg btn-outline-middle">Sign Up</button>
		        </div>
		      </div>      
		    </div>       
		    <div class="col-sm-4 col-xs-12">
		      <div class="panel panel-default text-center">
		        <div class="panel-heading">
		          <h1>Premium</h1>
		        </div>
		        <div class="panel-body">
		          <p><strong>100</strong> Lorem</p>
		          <p><strong>50</strong> Ipsum</p>
		          <p><strong>25</strong> Dolor</p>
		          <p><strong>10</strong> Sit</p>
		          <p><strong>Endless</strong> Amet</p>
		        </div>
		        <div class="panel-footer">
		          <h3>$49</h3>
		          <h4>per month</h4>
		          <button class="btn btn-lg btn-outline-primary">Sign Up</button>
		        </div>
		      </div>      
		    </div>    
		  </div>
		</div>

		<!-- Container (Contact Section) -->
		<div id="contact" class="container-fluid bg-grey">
		  <h2 class="text-center">CONTACT</h2>
		  <div class="row">
		    <div class="col-sm-5">
		      <p>Contact us and we'll get back to you within 24 hours.</p>
		      <p><span class="glyphicon glyphicon-map-marker"></span> Chicago, US</p>
		      <p><span class="glyphicon glyphicon-phone"></span> +00 1515151515</p>
		      <p><span class="glyphicon glyphicon-envelope"></span> myemail@something.com</p>
		    </div>
		    <div class="col-sm-7 slideanim">
		      <div class="row">
		        <div class="col-sm-6 form-group">
		          <input class="form-control" id="name" name="name" placeholder="Name" type="text" required>
		        </div>
		        <div class="col-sm-6 form-group">
		          <input class="form-control" id="email" name="email" placeholder="Email" type="email" required>
		        </div>
		      </div>
		      <textarea class="form-control" id="comments" name="comments" placeholder="Comment" rows="5"></textarea><br>
		      <div class="row">
		        <div class="col-sm-12 form-group">
		          <button class="btn btn-outline-middle pull-right" type="submit">Send</button>
		        </div>
		      </div>
		    </div>
		  </div>
		</div>
		<!-- <div class="top-header">
			<header class="container home">
			  <nav class="navbar navbar-default">
			    <div class="navbar-header">
			      <%= link_to 'Tent&Cateres', root_path, class: 'navbar-brand' %>
			    </div>
			    <% if admin_signed_in? %>
			      <div class="pull-right right-buttons">

			      	<ul class="lst-item">
			      		<li><i aria-hidden="true" class="fa fa-plus-circle"></i> <span>Accounts</span></li>
			      	</ul>
			        <%= link_to 'Sign out', destroy_admin_session_path, method: 'delete', class: 'btn btn-default navbar-btn logout' %>
			      </div>
			    <% else %>
			      <div class="pull-right right-buttons">
			      	<ul class="lst-item">
			      		<li><a href="/admins/sign_in">Login</a></li>
			      		<li><a href="/admins/sign_in">Price</a></li>
			      		<li><a href="/admins/sign_in">Demo Request</a></li>
			      		<li><a href="/admins/sign_in">Contact</a></li>
			      	</ul>
			      </div>

			    <% end %>		    
			  </nav>
			</header>
		</div> -->
		<!-- <div class="container">
		  <%= flash_messages if show_layout_flash? %>
		  <div class="row">
		    <%= yield %>
		  </div>
		</div> -->
  </body>
</html>
<script type="text/javascript">
	$('a[href*="#"]')
  // Remove links that don't actually link to anything
  .not('[href="#"]')
  .not('[href="#0"]')
  .click(function(event) {
    // On-page links
    if (
      location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') 
      && 
      location.hostname == this.hostname
    ) {
      // Figure out element to scroll to
      var target = $(this.hash);
      target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
      // Does a scroll target exist?
      if (target.length) {
        // Only prevent default if animation is actually gonna happen
        event.preventDefault();
        $('html, body').animate({
          scrollTop: target.offset().top
        }, 1000, function() {
          // Callback after animation
          // Must change focus!
          var $target = $(target);
          $target.focus();
          // if ($target.is(":focus")) { // Checking if the target was focused
          //   return false;
          // } else {
          //   $target.attr('tabindex','-1'); // Adding tabindex for elements not focusable
          //   $target.focus(); // Set focus again
          // };
        });
      }
    }
  });
</script>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>T&C</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>	
	<div class="container">
	  <%= flash_messages if show_layout_flash? %>
	  <div class="row">
	    <%= yield %>
	  </div>
	</div>
       
  </body>
</html>

</html>